### ISSUE TITLE
sshで、学内環境にトンネルを通してから、研究室のサーバにアクセスしたい

### ISSUE THREAD

**Issue by v97ug** [v97ug/question#10]
研究室のサーバにアクセスしたいけど、そのためには、学内環境を経由しないと研究室のサーバにアクセスできない。

家のパソコンから直接、研究室のサーバにアクセスするには、どうすればよいか。
その、トンネル？　を通せばいいのかな？

**Comment by nwtgck** [comment]
## 設定方法

自分のマシン（MacBook）とかの`.ssh/config`に以下を追記したら、
`ssh lab`ってすれば、パスワードを2回求められて、ラボもマシンに入れるはず

```
Host aizu
	User mXXXXXX
	HostName sshgate.u-aizu.ac.jp

Host lab
	User take
	HostName your_lab_hostname
	ProxyCommand ssh aizu nc %h %p
```


* `mXXXXXX`は自分の学籍
* `take`は研究室のマシンのユーザー名
* `your_lab_hostname`は研究室マシンのホスト名
* `ProxyCommand ssh aizu nc %h %p`の`aizu`は`Host aizu`と同じ名前にすれば任意に名付けられる
* `lab`は任意に名付けられる

## ssh方法

```sh
$ ssh lab
```

## [雑談] パスワードの入力の省略


パスワードが2回求められる
* 大学のネットワークに入るとき
* 研究室マシンのパスワード

（1回にしたかったら、研究室マシンに公開鍵でログインする設定をすれば、パスワードを打つ手間を省略できるとは思う）


こんなので、大丈夫かな？

**Comment by v97ug** [comment]
ありがとう！！
無事、研究室のマシンに接続できました(≧∇≦)b
