### ISSUE TITLE
jarファイルに、画像を突っ込むにはどうすればいいか。

### ISSUE THREAD

**Issue by v97ug** [v97ug/question#12]
jarファイルにエクスポートするときに画像も一緒にエクスポートしたのに、そのjarファイルを実行すると画像が読み込まれない。

現状、画像フォルダを別に作ってそこから画像を読み込むようにするしかない。

jarファイルを実行するときに、別な画像フォルダを使わずとも画像も表示できるようにするにはどうすればいいか。

**Comment by nwtgck** [comment]
僕も最近知った方法で、Javaで以下のようにすると、特別なリソースディレクトリからファイルが読み込めるようになったよ。

```java
getClass().getClassLoader().getResourceAsStream("img/item.png")
```


実際にActionGameJavaでjarにファイルに画像ファイルを取り込む方法で変更したプロジェクトを作ってみたから、試してみて（勝手にforkして作りました）。
https://github.com/nwtgck/ActionGameJava
どう変更すればいいかなるべく分かるようにコミットをしたつもりだから、変更履歴を見てみて

言語はJavaのままだけど、SBTのプロジェクトになってるよ。`sbt assembly`とするとjarファイルが生成されるよ（詳しくはREADME見てね）。そのjarファイルはポータブルだからどこか他の場所に移動しても画像ファイルを適切に読み込んでくれるよ。

SBTだと`src/main/resources/`というディレクトリにファイルを置いておくと、そこにファイルが`getResourceAsStream()`から読めるようになるみたい


もし、この変更を取り込みたいときは言って、プルリクエストします

**Comment by v97ug** [comment]
@nwtgck 
おー！！ありがとう！
これはすごい、超便利！
ぜひプルリクエストをお願いしますm(_ _)m
