### ISSUE TITLE
Ubuntuで、zipファイルをダブルクリックで展開するにはどうすればいいか。

### ISSUE THREAD

**Issue by v97ug** [v97ug/question#13]

**Comment by nwtgck** [comment]
ダブルクリックじゃなくて、右クリックで「Extract Here」または「ここに展開」じゃダメ？

<img width="354" alt="screen shot 2017-09-04 at 9 42 09" src="https://user-images.githubusercontent.com/10933561/30008048-a1e35ce4-9155-11e7-92d0-2caecd4d27c8.png">

**Comment by v97ug** [comment]
@nwtgck どうしてもダブルクリックでやりたい。
「ここに展開」はいつもやってて、Macみたいに簡単にzipファイルを展開できたらいいなって思ったから、Ubuntuでもダブルクリックで展開したい。

**Comment by nwtgck** [comment]
方法を探してみたよ。できたから書いてみるね

# 基本的な戦略

ダブルクリックして起動するアプリケーションを任意のシェルスクリプトにしてしまう方法。
つまり、zipだけではなく、他のことにも応用できる汎用的な方法。

（参考：https://ubuntuforums.org/showthread.php?t=1149401）

# やりかた

## `foo.desktop`の作成

`/usr/share/applications`に`foo.desktop`のファイルを作る

以下は`foo.desktop`の中身
（注意：作成するときはsudoを忘れずに）

```desktop
[Desktop Entry]
Name=foo
Exec=/usr/bin/foo.sh %U
Terminal=false
Type=Application
MimeType=application/zip;
```

もちろん名前はfooじゃなくてもOK
（参考：https://askubuntu.com/questions/525953/use-custom-command-to-open-files）

## application/zipなもののデフォルトオープンにする

以下のコマンドを打つ

```sh
$ xdg-mime default foo.desktop "application/zip"
``` 

（ログアウトしても有効なのかは未検証）

## `foo.sh`を作る

`foo.sh`はzipを解凍するスクリプト。
中身は、

```bash
#!/bin/bash
/usr/bin/unzip -d $(dirname $1) $1;
```

* `unzip`の `-d`オプションは展開先のディレクトリ指定
* `dirname`はファイルパスから親ディレクトリを取得する（元から入っているコマンドぽい）

`/usr/bin/`の中に移動させる

```sh
$ sudo mv foo.sh /usr/bin/
```

### `foo.sh`の問題点

展開先のディレクトリに空白が入っていると展開できない。おそらくエスケープしないといけない文字列を含んだパス名だと展開ができないこと。`unzip`の`-d`オプション自体がスペースが入ったディレクトリを指定できないぽく、`unzip -d "/home/user1/Untiled  Folder" my.zip`みたいなのを展開できない。`unzip`コマンドの問題なので、頑張ればzip解凍できるはず。（任意のスクリプトを実行できるからCでもRubyでも好きなプログラミング言語を実行してもいいと思う）


これで完成！

## デモ

![unzip](https://user-images.githubusercontent.com/10933561/30041552-f01da632-9225-11e7-957f-438f57147ad3.gif)

## その他参考になったところ
* dirnameで取得文字列にダブルクォートをつけたいときの参考 - https://stackoverflow.com/a/8426110/2885946

**Comment by v97ug** [comment]
@nwtgck ありがとおおお
無事にダブルクリックでzipを展開できました！
ちなみに、僕はfile-rollerコマンドを使って、さらに空白文字の問題を解決するために$1をダブルクウォートで囲んでみた。
```bash
#!/bin/bash
/usr/bin/file-roller -h "$1";
```

いつもわかりやすい解説ありがとうヽ(*＾∇＾*)ノ*

**Comment by nwtgck** [comment]
`file-roller`知らなかった！情報ありがとう
