### ISSUE TITLE
Haskellで、リファクタリングする方法

### ISSUE THREAD

**Issue by v97ug** [v97ug/question#5]
変数名を一括で変えられる機能を、Haskellでも使いたいのですが、IntelliJなどでプラグインを入れても、思ったような動作をしません。

Haskellでリファクタリングできるツールなどあれば、教えていただきたいです。

**Comment by nwtgck** [comment]
intellij-haskellを最近試したときに、進化しててリファクタリング（識別子名の変更）が可能になってたよ

ただRunボタンとかが機能しないだよね。作ってる人に聞いても、まだ実装できてないってことだから、今後に期待してるところ


下のgifが実際にリファクタリングしたやつだよ
![ih](https://cloud.githubusercontent.com/assets/10933561/23982940/3e2af870-0a54-11e7-94ee-1c1a1d404645.gif)


あと、定義にジャンプするやつも使えるようになってて捗るよ

Haskellのプラグインは2種類あるうちで、こっちのほう（https://github.com/rikvdkleij/intellij-haskell）

**Comment by v97ug** [comment]
@nwtgck 
ありがとう！
Ubuntu 16.04LTSでやったらとても上手くいったけど、mac OS Sierraだと上手くいかなかった(T ^ T)
intellij-haskellを入れて、IntelliJを再起動したら、以下のエラーメッセージが出てきた。

<img width="1440" alt="2017-03-19 17 08 15" src="https://cloud.githubusercontent.com/assets/15831991/24079253/addf1402-0cc6-11e7-8e65-048d5286b173.png">

> Something went wrong while calling hlint. Error: No compiler found, expected minor version match with ghc-8.0.2 (x86_64) (based on resolver setting in /Users/v97ug/dev/haskell/free-game/TestHaskell3/stack.yaml). To install the correct GHC into /Users/v97ug/.stack/programs/x86_64-osx/, try running "stack setup" or use the "--install-ghc" flag. To use your system GHC installation, run "stack config set system-ghc --global true", or use the "--system-ghc" flag.

**Comment by nwtgck** [comment]
なんか「No compiler found」とかでてるね
コンパイラ(GHC)を入れたらいいのかな
macだとstack使ってる？

以下のコマンドで、うまいことGHCがインストールされるかも

```sh
$ stack setup
```

もしくは、

`stack setup --install-ghc`

**Comment by v97ug** [comment]
`stack setup --install-ghc` でやったら、上手くGHCが入って、リファクタリングができるようになった( ´ ▽ ` )

**Comment by nwtgck** [comment]
よかったよかった
